/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GsapPhoto: typeof import('./src/components/GsapPhoto.vue')['default']
    IndigoFooter: typeof import('./src/components/IndigoFooter.vue')['default']
    PeopleState: typeof import('./src/components/PeopleState.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCarousel: typeof import('./src/components/SwiperCarousel.vue')['default']
  }
}
